### ISSUE TITLE
Failure to read json data

### ISSUE THREAD

**Issue by nimaft** [ansible-lockdown/AMAZON2023-CIS-Audit#3]
**Describe the Issue**
When I run goss, the audit fails and my audit file includes the below error:
<code>Error: could not read json data in /tmp/AMAZON2023-CIS-Audit/section_1/cis_1.1/cis_1.1.1.1.yml: could not unmarshal "---\n\n\n  \ncommand:\n  squashfs:\n    title: 1.1.1.1 | Ensure mounting of squashfs filesystems is disabled | modprobe\n    exit-status: 0\n    exec: \"modprobe -n -v squashfs | grep -E '(squashfs|install)'\"\n    stdout:\n    - install /bin/true\n    meta:\n      server: 2\n      workstation: NA\n      CIS_ID: 1.1.1.1\n      CISv8:\n      - 4.8\n      CISv8_IG1: false\n     CISv8_IG2: true\n      CISv8_IG3: true\n      NISTSP800-53-R5: CM-7\nfile:\n  blacklist_squashfs:\n    title: 1.1.1.1 | Ensure mounting of squashfs filesystems is disabled | blacklist\n    exists: true\n    path: /etc/modprobe.d/blacklist.conf\n    contents:\n    - '/^blacklist squashfs/'\n    meta:\n      server: 2\n      workstation: NA\n      CIS_ID: 1.1.1.1\n      CISv8:\n      - 4.8\n      CISv8_IG1: false\n      CISv8_IG2: true\n      CISv8_IG3: true\n      NISTSP800-53-R5: CM-7\n  \n\n" as YAML data: invalid Attribute for File:blacklist_squashfs: path
</code>
I thought maybe there is an issue with `cis_1.1/cis_1.1.1.1.yml` so I skipped it and figured its the same with other files (I checked two more). I have the same setup for AL2 audit and it works as expected.

**Expected Behavior**
I expect the audit file to include the result of the audit including the failed controls and applied controls.

**Actual Behavior**
Error message indicated above.

**Control(s) Affected**
N/A

**Environment (please complete the following information):**

- branch being used: main
- Ansible Version: ansible [core 2.15.3]
- Host Python Version: Python 3.9.16
- Ansible Server Python Version: N/A
- Additional Details:

**Additional Notes**
Apparently invalid attributes are used in audit templates (`path/file`, `path/contents`, and `mount/mountpoints`)

**Possible Solution**
View #4

**Comment by zadowsmash** [comment]
I am also experiencing exactly the same issue.

**Comment by nimaft** [comment]
> I am also experiencing exactly the same issue.

I fixed the problem and created a PR you can find here: #4 

Would be great if one of the maintainers review and merge. cc: @uk-bolly

**Comment by nimaft** [comment]
Fixed in #8
